### ISSUE TITLE
Phaser invalid document exception

### ISSUE THREAD

**Issue by averdion** [Thibaut/devdocs#283]
On running phaser scraper, an error is raised:
```URL: http://phaser.io/docs/2.4.1/index
/home/desarrollo/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.2.1/lib/html/pipeline/filter.rb:66:in `html': HTML::Pipeline::Filter::InvalidDocumentException (HTML::Pipeline::Filter::InvalidDocumentException)
	from /home/desarrollo/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.2.1/lib/html/pipeline/filter.rb:59:in `doc'```

**Comment by Thibaut** [comment]
I'll fix this next time I update Phaser.
