### ISSUE TITLE
Trouble running thor docs:list to test for the scraper

### ISSUE THREAD

**Issue by calebkleveter** [Thibaut/devdocs#369]
I am trying to test for the scrapers to see if they are listed, but when I run `thor docs:list`, I am getting this error:

```
/home/ubuntu/workspace/devdocs/lib/docs/core/filter_stack.rb:48:in `const_get': uninitialized constant Docs::Haml::CleanHtmlFilter (NameError)
Did you mean?  Docs::CleanHtmlFilter
               Docs::InnerHtmlFilter
               Docs::CleanTextFilter
        from /home/ubuntu/workspace/devdocs/lib/docs/core/filter_stack.rb:48:in `filter_const'
        from /home/ubuntu/workspace/devdocs/lib/docs/core/filter_stack.rb:46:in `map'
        from /home/ubuntu/workspace/devdocs/lib/docs/core/filter_stack.rb:46:in `filter_const'
        from /home/ubuntu/workspace/devdocs/lib/docs/core/filter_stack.rb:13:in `push'
        from /home/ubuntu/workspace/devdocs/lib/docs/scrapers/haml.rb:12:in `<class:Haml>'
        from /home/ubuntu/workspace/devdocs/lib/docs/scrapers/haml.rb:2:in `<module:Docs>'
        from /home/ubuntu/workspace/devdocs/lib/docs/scrapers/haml.rb:1:in `<top (required)>'
        from /home/ubuntu/workspace/devdocs/lib/docs.rb:34:in `require'
        from /home/ubuntu/workspace/devdocs/lib/docs.rb:34:in `const_get'
        from /home/ubuntu/workspace/devdocs/lib/docs.rb:34:in `block in all'
        from /home/ubuntu/workspace/devdocs/lib/docs.rb:34:in `map'
        from /home/ubuntu/workspace/devdocs/lib/docs.rb:34:in `all'
        from /home/ubuntu/workspace/devdocs/lib/tasks/docs.thor:16:in `list'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/runner.rb:36:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/bin/thor:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/thor:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/thor:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

I have tried running in both the `scraper` and root directories for the project, but neither work.

**Comment by Thibaut** [comment]
This is because the class `Docs::Haml::CleanHtmlFilter` doesn't exist, but `Docs::Haml` is trying to use it as a filter (via `html_filters.push 'haml/clean_html'`).

Make sure the class is defined in `lib/docs/filters/haml/clean_html.rb`

**Comment by Thibaut** [comment]
I'm guessing you're trying to add a new scraper (there isn't one for Haml yet). If you're not, delete `lib/docs/scrapers/haml.rb`.

**Comment by calebkleveter** [comment]
New error:

```
/home/ubuntu/workspace/devdocs/lib/tasks/docs.thor:9:in `require': cannot load such file -- docs (LoadError)
        from /home/ubuntu/workspace/devdocs/lib/tasks/docs.thor:9:in `initialize'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:355:in `new'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:355:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/runner.rb:36:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/bin/thor:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/thor:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/thor:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Thibaut** [comment]
Hmm, that one makes no sense. Are you running the command from `/home/ubuntu/workspace/devdocs/`? Did you edit `lib/docs.rb`?

**Comment by calebkleveter** [comment]
I just ran the command again and it works. Funny.

Thanks for the help!
