### ISSUE TITLE
Problem to install devdocs on windows

### ISSUE THREAD

**Issue by dam3313** [Thibaut/devdocs#486]
Hello,

I'm trying to install devdocs on Windows for a local network,  but when I run the server I have the following error:
'test@DESKTOP-BHUEPN0 MINGW64 ~/Documents/devdocs (master)
$ rackup
2016-09-14 22:14:36 - ExecJS::ProgramError - TypeError: Object doesn't support this property or method:
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:21:in `eval'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:46:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:78:in `compile'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/coffee_script_processor.rb:21:in `block in call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cache.rb:85:in `fetch'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/coffee_script_processor.rb:20:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:23:in `block in call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/utils.rb:196:in `dfs'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:24:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/base.rb:66:in `find_asset'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/environment.rb:30:in `find_asset'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/base.rb:92:in `[]'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-helpers-1.2.1/lib/sprockets/helpers.rb:351:in `find_asset_path'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-helpers-1.2.1/lib/sprockets/helpers.rb:145:in `asset_path'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-helpers-1.2.1/lib/sprockets/helpers.rb:158:in `asset_tag'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-helpers-1.2.1/lib/sprockets/helpers.rb:171:in `javascript_tag'
        C:/Users/test/Documents/devdocs/views/index.erb:30:in `block in singleton class'
        C:/Users/test/Documents/devdocs/views/index.erb:-6:in `instance_eval'
        C:/Users/test/Documents/devdocs/views/index.erb:-6:in `singleton class'
        C:/Users/test/Documents/devdocs/views/index.erb:-8:in `__tilt_17702920'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `evaluate'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:823:in `render'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-contrib-1.4.7/lib/sinatra/engine_tracking.rb:91:in `block in render'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-contrib-1.4.7/lib/sinatra/engine_tracking.rb:83:in `with_engine'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-contrib-1.4.7/lib/sinatra/engine_tracking.rb:91:in `render'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:667:in `erb'
        C:/Users/test/Documents/devdocs/lib/app.rb:225:in `block in <class:App>'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:84:in `protected_app_call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:79:in `better_errors_call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:57:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:53:in `process'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:39:in `receive_data'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1-x64-mingw32/lib/eventmachine.rb:194:in `run_machine'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1-x64-mingw32/lib/eventmachine.rb:194:in `run'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
        C:/Ruby23-x64/bin/rackup:23:in `load'
        C:/Ruby23-x64/bin/rackup:23:in `<main>'
::1 - - [14/Sep/2016:22:14:36 +0200] "GET / HTTP/1.1" 500 - 0.7497
::1 - - [14/Sep/2016:22:14:36 +0200] "POST /__better_errors/712701b748d28bd9/variables HTTP/1.1" 200 - 0.0160
'
I have found that is related to the index.erb file but I can't find a solution.

**Comment by dam3313** [comment]
It's finally working, I don't know why but it's works.
