### ISSUE TITLE
"thor" step fails

### ISSUE THREAD

**Issue by battlesnake** [Thibaut/devdocs#619]
I follow the process from the README:

```
git clone https://github.com/Thibaut/devdocs.git && cd devdocs
gem install bundler
bundle install
thor docs:download --default # fails
rackup # not run
```

The "thor" step fails with:

```
/usr/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem thor (>= 0.a) (Gem::GemNotFoundException)
        from /usr/lib/ruby/2.4.0/rubygems.rb:258:in `bin_path'
        from /home/mark/.gem/ruby/2.3.0/bin/thor:22:in `<main>'
```

Extra info:

```
Distro: Arch

git rev-parse HEAD
a3e8a4ed99c0c46a290b0ad65b2a0cf28d0348e9

uname -a
Linux hai 4.10.8-mark #2 SMP PREEMPT Wed Apr 5 13:28:44 BST 2017 x86_64 GNU/Linux

ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

gem --version
2.6.11

bundle --version
Bundler version 1.14.6

thor --version
/usr/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem thor (>= 0.a) (Gem::GemNotFoundException)
        from /usr/lib/ruby/2.4.0/rubygems.rb:258:in `bin_path'
        from /home/mark/.gem/ruby/2.3.0/bin/thor:22:in `<main>'
```

I'm not familiar with Ruby's tooling at all

**Comment by Thibaut** [comment]
Looks like you've got two versions of Ruby installed and for some reason they get mixed up.

Does it work if you do `bundle exec thor` instead of `thor`?

**Comment by battlesnake** [comment]
Prefixing with `bundle exec` worked great thanks, it might be worth suggesting this in the README for people like me who just want to run locally (without depending on browser caching) and aren't familiar with Ruby tools.

```
mark:~/repos/devdocs $ bundle exec thor docs:download --default
(1/6) DOM Events OK
(2/6) HTML OK
(3/6) CSS OK
(4/6) HTTP OK
(5/6) JavaScript OK
(6/6) DOM OK
Done

mark:~/repos/devdocs $ bundle exec rackup
/home/mark/repos/devdocs/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/server.rb:107: warning: constant ::Fixnum is deprecated
Thin web server (v1.7.0 codename Dunder Mifflin)
Maximum connections set to 1024
Listening on localhost:9292, CTRL+C to stop
```

**Comment by Thibaut** [comment]
👍 b6fc76f59e233a7cb12524396e3d4f39388da5c4
