### ISSUE TITLE
NameError - uninitialized constant Rack::File::Iterator:

### ISSUE THREAD

**Issue by guillaume-chevalier** [Thibaut/devdocs#771]
Basically, I cloned the repo in a new folder since the first time I installed it on a stupid hard drive that crashes on linux because of NTFS issues. Now, the new cloned repo won't start or install properly. 

```
gui@debian:/home/users_home/Documents/GIT/devdocs$ bundle install
Using rake 12.3.1
Using concurrent-ruby 1.0.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.1.5
Using backports 3.11.1
Using coderay 1.1.2
Using erubi 1.7.1
Using rack 2.0.4
Using better_errors 2.4.0
Using browser 2.5.3
Using bundler 1.16.1
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using coffee-script 2.4.1
Using daemons 1.2.6
Using ffi 1.9.23
Using ethon 0.11.0
Using eventmachine 1.2.5
Using exifr 1.3.3
Using fspath 3.1.0
Using highline 1.7.10
Using mini_portile2 2.3.0
Using nokogiri 1.8.2
Using html-pipeline 2.7.1
Using image_size 1.5.0
Using in_threads 1.5.0
Using progress 3.4.0
Using image_optim 0.26.1
Using image_optim_pack 0.5.0.20180124 (x86_64-linux)
Using method_source 0.9.0
Using multi_json 1.13.1
Using mustermann 1.0.2
Using options 2.3.2
Using progress_bar 1.2.0
Using pry 0.11.3
Using rack-protection 2.0.1
Using rack-test 0.8.3
Using rb-fsevent 0.10.3
Using rb-inotify 0.9.10
Using rr 1.2.1
Using sass-listen 4.0.0
Using sass 3.5.6
Using tilt 2.0.8
Using sinatra 2.0.1
Using sinatra-contrib 2.0.1
Using sprockets 3.7.1
Using sprockets-helpers 1.2.1
Using unicode-display_width 1.3.0
Using unicode_utils 1.4.0
Using strings 0.1.1
Using thin 1.7.2
Using thor 0.20.0
Using tty-screen 0.6.4
Using tty-which 0.3.0
Using tty-pager 0.11.0
Using typhoeus 1.3.0
Using uglifier 4.1.8
Using unix_utils 0.0.15
Using yajl-ruby 1.3.1
Bundle complete! 27 Gemfile dependencies, 62 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

```
gui@debian:/home/users_home/Documents/GIT/devdocs$ bundle exec thor docs:download --default
(1/6) HTML OK
(2/6) DOM Events OK
(3/6) JavaScript OK
(4/6) HTTP OK
(5/6) CSS OK
(6/6) DOM OK
Done
```

```
gui@debian:/home/users_home/Documents/GIT/devdocs$ bundle exec rackup
/usr/lib/ruby/vendor_ruby/thin/server.rb:107: warning: constant ::Fixnum is deprecated
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:9292, CTRL+C to stop
2018-03-23 05:04:26 - NameError - uninitialized constant Rack::File::Iterator:
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:261:in `body'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1084:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
	/var/lib/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:84:in `protected_app_call'
	/var/lib/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:79:in `better_errors_call'
	/var/lib/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:57:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/path_traversal.rb:16:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/json_csrf.rb:18:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/base.rb:49:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/base.rb:49:in `call'
	/usr/lib/ruby/vendor_ruby/rack/logger.rb:15:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:224:in `call'
	/usr/lib/ruby/vendor_ruby/rack/head.rb:13:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:66:in `block in call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
	/usr/lib/ruby/vendor_ruby/rack/tempfile_reaper.rb:15:in `call'
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:49:in `_call'
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:37:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/show_exceptions.rb:23:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/common_logger.rb:33:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:231:in `call'
	/usr/lib/ruby/vendor_ruby/rack/chunked.rb:54:in `call'
	/usr/lib/ruby/vendor_ruby/rack/content_length.rb:15:in `call'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:86:in `block in pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `catch'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
	/usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
	/usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
	/usr/lib/ruby/vendor_ruby/rack/handler/thin.rb:19:in `run'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:297:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:148:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/bin/rackup:4:in `<top (required)>'
	/usr/local/bin/rackup:23:in `load'
	/usr/local/bin/rackup:23:in `<main>'
Unexpected error while processing request: undefined method `bytesize' for Rack::Utils:Module
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:713:in `block in each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `block in each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `each'
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:708:in `each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `each'
	/usr/lib/ruby/vendor_ruby/rack/chunked.rb:23:in `each'
	/usr/lib/ruby/vendor_ruby/thin/response.rb:96:in `each'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:114:in `post_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
	/usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
	/usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
	/usr/lib/ruby/vendor_ruby/rack/handler/thin.rb:19:in `run'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:297:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:148:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/bin/rackup:4:in `<top (required)>'
	/usr/local/bin/rackup:23:in `load'
	/usr/local/bin/rackup:23:in `<main>'

::1 - - [23/Mar/2018:05:04:26 -0400] "GET / HTTP/1.1" 500 - 0.1650
2018-03-23 05:04:26 - NameError - uninitialized constant Rack::File::Iterator:
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:261:in `body'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1084:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
	/var/lib/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:84:in `protected_app_call'
	/var/lib/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:79:in `better_errors_call'
	/var/lib/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:57:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/path_traversal.rb:16:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/json_csrf.rb:18:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/base.rb:49:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/base.rb:49:in `call'
	/usr/lib/ruby/vendor_ruby/rack/logger.rb:15:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:224:in `call'
	/usr/lib/ruby/vendor_ruby/rack/head.rb:13:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:66:in `block in call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
	/usr/lib/ruby/vendor_ruby/rack/tempfile_reaper.rb:15:in `call'
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:49:in `_call'
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:37:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/show_exceptions.rb:23:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/common_logger.rb:33:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:231:in `call'
	/usr/lib/ruby/vendor_ruby/rack/chunked.rb:54:in `call'
	/usr/lib/ruby/vendor_ruby/rack/content_length.rb:15:in `call'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:86:in `block in pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `catch'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
	/usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
	/usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
	/usr/lib/ruby/vendor_ruby/rack/handler/thin.rb:19:in `run'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:297:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:148:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/bin/rackup:4:in `<top (required)>'
	/usr/local/bin/rackup:23:in `load'
	/usr/local/bin/rackup:23:in `<main>'
Unexpected error while processing request: undefined method `bytesize' for Rack::Utils:Module
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:713:in `block in each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `block in each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `each'
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:708:in `each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `each'
	/usr/lib/ruby/vendor_ruby/rack/chunked.rb:23:in `each'
	/usr/lib/ruby/vendor_ruby/thin/response.rb:96:in `each'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:114:in `post_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
	/usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
	/usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
	/usr/lib/ruby/vendor_ruby/rack/handler/thin.rb:19:in `run'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:297:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:148:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/bin/rackup:4:in `<top (required)>'
	/usr/local/bin/rackup:23:in `load'
	/usr/local/bin/rackup:23:in `<main>'

::1 - - [23/Mar/2018:05:04:26 -0400] "GET / HTTP/1.1" 500 - 0.0177
2018-03-23 05:04:26 - NameError - uninitialized constant Rack::File::Iterator:
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:261:in `body'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1084:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
	/var/lib/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:84:in `protected_app_call'
	/var/lib/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:79:in `better_errors_call'
	/var/lib/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:57:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/path_traversal.rb:16:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/json_csrf.rb:18:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/base.rb:49:in `call'
	/usr/lib/ruby/vendor_ruby/rack/protection/base.rb:49:in `call'
	/usr/lib/ruby/vendor_ruby/rack/logger.rb:15:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:224:in `call'
	/usr/lib/ruby/vendor_ruby/rack/head.rb:13:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:66:in `block in call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
	/usr/lib/ruby/vendor_ruby/rack/tempfile_reaper.rb:15:in `call'
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:49:in `_call'
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:37:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/show_exceptions.rb:23:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/common_logger.rb:33:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:231:in `call'
	/usr/lib/ruby/vendor_ruby/rack/chunked.rb:54:in `call'
	/usr/lib/ruby/vendor_ruby/rack/content_length.rb:15:in `call'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:86:in `block in pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `catch'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
	/usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
	/usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
	/usr/lib/ruby/vendor_ruby/rack/handler/thin.rb:19:in `run'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:297:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:148:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/bin/rackup:4:in `<top (required)>'
	/usr/local/bin/rackup:23:in `load'
	/usr/local/bin/rackup:23:in `<main>'
Unexpected error while processing request: undefined method `bytesize' for Rack::Utils:Module
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:713:in `block in each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `block in each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `each'
	/usr/lib/ruby/vendor_ruby/rack/lint.rb:708:in `each'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/body_proxy.rb:36:in `each'
	/usr/lib/ruby/vendor_ruby/rack/chunked.rb:23:in `each'
	/usr/lib/ruby/vendor_ruby/thin/response.rb:96:in `each'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:114:in `post_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
	/usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
	/usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
	/usr/lib/ruby/vendor_ruby/rack/handler/thin.rb:19:in `run'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:297:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:148:in `start'
	/var/lib/gems/2.5.0/gems/rack-2.0.4/bin/rackup:4:in `<top (required)>'
	/usr/local/bin/rackup:23:in `load'
	/usr/local/bin/rackup:23:in `<main>'

::1 - - [23/Mar/2018:05:04:26 -0400] "GET / HTTP/1.1" 500 - 0.0191
```

BTW sorry I didn't take the time to read the CONTRIBUTING.md. Hope this stack trace helps.

**Comment by j-f1** [comment]
What does `ruby -v` output for you?

**Comment by guillaume-chevalier** [comment]
I don't need to use devdocs anymore now. Still, here is what you asked for: 

```
$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux-gnu]
```
